# -------- STAGE 1: Build --------
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

COPY . .

RUN mvn clean package -pl services/order-service -am -DskipTests


# -------- STAGE 2: Run --------
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY --from=builder /app/services/order-service/target/*.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]